# MASTERY MACHINE LEARNING

## Chapter 2: Python Ecosystem for Machine Learning

In [ ]:
!python --version

In [10]:
!pip install --upgrade --user scipy matplotlib pandas

    black (>=20.) ; extra == 'dev'
          ~~~~~^
    black (>=20.) ; extra == 'dev'
          ~~~~~^


In [11]:
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))

scipy: 1.16.1
numpy: 2.3.2
matplotlib: 3.10.5
pandas: 2.3.1


In [15]:
!pip install --upgrade --user scikit-learn

    black (>=20.) ; extra == 'dev'
          ~~~~~^
    black (>=20.) ; extra == 'dev'
          ~~~~~^


In [16]:
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

sklearn: 1.7.1


## Chapter 3 Crash Course in Python and SciPy

### 3.1 Python Crash Course
#### 3.1.1 Assignment

In [18]:
# Strings
data = 'hello world'
print(data[0])
print(len(data))
print(data)


h
11
hello world


### 3.1.2 Flow Control

In [19]:
# If-Then-Else Conditional
value = 99
if value == 99:
    print('That is fast')
elif value > 200:
    print('That is too fast')
else:
    print('That is safe')

That is fast


## Chapter 4 How To Load Machine Learning Data

In [25]:
!ls ../data

Early Stage Diabetes Risk Prediction - UCI Machine Learning Repository.html
README.md
diabetes_data_upload.csv
early+stage+diabetes+risk+prediction+dataset.zip
pima-indians-diabetes.csv
pima-indians-diabetes.data.csv
pima-indians-diabetes.names


In [33]:
# Load CSV Using Python Standard Library
import csv
import numpy as np
from IPython.display import display

filename = '../data/pima-indians-diabetes.data.csv'
raw_data = open(filename, 'rt')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x = list(reader)
data = np.array(x).astype('float')

print(data.shape)
display(data)

(768, 9)


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

In [35]:
# Load CSV using NumPy
import numpy as np # loadtxt
filename = '../data/pima-indians-diabetes.data.csv'
raw_data = open(filename, 'rb')
data = np.loadtxt(raw_data, delimiter=",")
print(data.shape)
display(data)

(768, 9)


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

In [39]:
!pip install --upgrade urllib

ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib


In [42]:
import urllib.request

In [46]:
# Load CSV from URL using NumPy
from numpy import loadtxt
# from urllib import urlopen
import urllib.request
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/refs/heads/master/pima-indians-diabetes.data.csv'
raw_data = urllib.request.urlopen(url)
dataset = loadtxt(raw_data, delimiter=",")
print(dataset.shape)
display(dataset)

(768, 9)


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]],
      shape=(768, 9))

## Kết thúc

In [21]:
!jupyter nbconvert python101_mlproj_250806.ipynb --to html --output=python101_mlproj_250806_v0.html

[NbConvertApp] Converting notebook python101_mlproj_250806.ipynb to html
[NbConvertApp] Writing 592029 bytes to python101_mlproj_250806_v0.html
